#!/bin/bash

#installation des dépendances
sudo apt-get install -y python-gi libnotify-dev sox alsa-utils

#création du dossier dans /usr/share
if [[ -d "/usr/share/google2ubuntu" ]];then
	sudo rm -r /usr/share/google2ubuntu/
	sudo mkdir /usr/share/google2ubuntu/
else
	sudo mkdir /usr/share/google2ubuntu/
fi

# création du dossier de config
if [[ ! -d $HOME/.config/google2ubuntu/ ]]; then
	mkdir $HOME/.config/google2ubuntu/	
fi

# suppression des anciens lanceurs
if [[ -f /usr/share/applications/google2ubuntu.desktop ]]; then
	sudo rm /usr/share/applications/google2ubuntu.desktop
fi

if [[ -f /usr/share/applications/google2ubuntu-gui.desktop ]]; then
	sudo rm /usr/share/applications/google2ubuntu-gui.desktop
fi

# copie des fichiers
chmod +x google2ubuntu.py
chmod +x google2ubuntu-manager.py 
chmod +x record.sh

sudo cp google2ubuntu.py /usr/share/google2ubuntu/
sudo cp google2ubuntu-manager.py /usr/share/google2ubuntu/
sudo cp record.sh /usr/share/google2ubuntu/
sudo cp icons.png /usr/share/google2ubuntu/
sudo cp google2ubuntu.desktop /usr/share/applications/
sudo cp google2ubuntu-gui.desktop /usr/share/applications/
sudo cp LICENSE /usr/share/google2ubuntu/
sudo cp sound.wav /usr/share/google2ubuntu/
sudo cp default.conf /usr/share/google2ubuntu/
cp -r modules/ $HOME/.config/google2ubuntu/

exit 0
