#!/bin/bash

if [[ -d "/usr/share/google2ubuntu/" ]]; then
	sudo rm -r /usr/share/google2ubuntu
fi

if [[ -f "/usr/share/applications/google2ubuntu.desktop" ]]; then
	sudo rm /usr/share/applications/google2ubuntu.desktop 
fi

if [[ -f "/usr/share/applications/google2ubuntu-gui.desktop" ]]; then
	sudo rm /usr/share/applications/google2ubuntu-gui.desktop 
fi
